### ISSUE TITLE
Flow control

### ISSUE THREAD

**Issue by ekr** [ekr/minq#19]
Connection-level flow control (MAX_DATA, MAX_STREAM_ID frames). The intent, at this point, is to provide reasonable limits to traffic burstiness and expect peers to respect them. A non-goal is to fine-tune the algorithms that generate optimal flow control limits.

Stream level flow control (MAX_STREAM_DATA). See note above.

**Comment by martinthomson** [comment]
I have an implementation in #61.  It's not perfect, but I think that it's a solid start.
