### ISSUE TITLE
Implementation of SetExtensionHandler missing

### ISSUE THREAD

**Issue by boisjacques** [ekr/minq#22]
The function SetExtensionHandler in tls.go:76 is not implemented. Therefore the example client and server implementations aren't working.

**Comment by pietdevaere** [comment]
I'm experiencing the same issue while trying to set up minq.

**Comment by pietdevaere** [comment]
```
# github.com/ekr/minq
./tls.go:76:7: c.tls.SetExtensionHandler undefined (type *mint.Conn has no field or method SetExtensionHandler)
FAIL	github.com/ekr/minq [build failed]
```

**Comment by ekr** [comment]
Oh, the instructions have bit rotted. Try Mint master.

**Comment by pietdevaere** [comment]
That works. Thanks!
